openapi: "3.0.0"
info:
  title: "API de gestion des produits"
  version: "1.0.0"

servers:
  - url: "http://localhost:8080"
    description: "Serveur local"

tags:
  - name: "produit"
    description: "Gestion des produits"

paths:
  /produit:
    get:
      tags:
        - "produit"
      summary: "Lister les produits"
      description: "Récupère tous les produits disponibles"
      operationId: "getAllProduits"
      responses:
        "200":
          description: "Liste des produits récupérée avec succès"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Produit"

    post:
      tags:
        - "produit"
      summary: "Ajouter un produit"
      description: "Ajoute un nouveau produit au catalogue"
      operationId: "addProduit"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Produit"
      responses:
        "201":
          description: "Produit ajouté avec succès"
          content:
            application/json:
              schema:
                type: "string"

    patch:
      tags:
        - "produit"
      summary: "Modifier un produit"
      description: "Modifie un produit existant"
      operationId: "updateProduit"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Produit"
      responses:
        "204":
          description: "Produit modifié avec succès"

  /produit/{code}:
    get:
      tags:
        - "produit"
      summary: "Obtenir un produit par code"
      description: "Récupère les détails d'un produit en fonction de son code unique"
      operationId: "getProduitByCode"
      parameters:
        - name: "code"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "Détails du produit récupérés avec succès"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Produit"
        "404":
          description: "Produit non trouvé"

components:
  schemas:
    Produit:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          example: 1
        code:
          type: "string"
          example: "PRD001"
        libelle:
          type: "string"
          example: "Ordinateur portable"
        prixVente:
          type: "number"
          format: "double"
          example: 999.99
        quantite:
          type: "integer"
          example: 50
        quantiteInitiale:
          type: "integer"
          example: 100
